name: linkedin_login_ios
description: "Contains iOS specific code"
version: 0.0.3
homepage: https://github.com/d3xt3r2909/linkedin_login/tree/master/linkedin_login_ios
repository: https://github.com/d3xt3r2909/linkedin_login
documentation:
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.22.0
  linkedin_login_platform_interface:
    git:
      url: https://github.com/alikaradogan/linkedin_login
      path: linkedin_login_ios

dev_dependencies:
  flutter_test:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  pigeon: ^25.3.2
  mocktail: ^1.0.4
  args: ^2.7.0

flutter:
  plugin:
    implements: linkedin_login
    platforms:
      ios:
        dartPluginClass: LinkedinLoginIos
